version: 2

models:
  - name: landing_alarm_v2
    description: "This table contains the alarm data from all wenco devices"
    columns:
      - name: alert_id
        description: "key field for alerts"
        tests:
          - not_null
      - name: asset_id
        description: "key field for assets"
        tests:
          - not_null
      - name: alarm_id
        description: "key field for alarms"
        tests:
          - not_null
      - name: activated_at
        description: "The time when the alarm got activated."
        tests:
          - dbt_utils.expression_is_true:
              expression: "activated_at <= current_timestamp"
      - name: deactivated_at
        description: "The time when the alarm got deactivated."
        tests:
          - dbt_utils.expression_is_true:
              expression: "try_to_timestamp(deactivated_at) is not null"

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - asset_id
            - alarm_id
            - activated_at
             